Add code execution
CS3219-AY2425S1/cs3219-ay2425s1-project-g35 pull request #60
Opened 2024-11-07 20:08 UTC by alex-setyawan

Added:
- code execution logic
- default templates
- reset button

2024-11-08 16:19 UTC, seewhyjay reviewed
Seems like this can be done within the frontend without the need for a microservice

2024-11-08 17:39 UTC, seewhyjay commented on ExecutionService/app.js
> +
Just call this endpoint in the frontend, and do the same error handling there

2024-11-08 17:39 UTC, seewhyjay requested changes
Just call this endpoint in the frontend, and do the same error handling there

2024-11-09 15:44 UTC, lambraydon approved these changes
LGTM

2024-11-09 15:45 UTC, seewhyjay approved these changes

2024-11-09 15:56 UTC, merged